name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"
          pip install -r operations_milestones/requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}


      - name: TeX build
        shell: bash
        env:
          JIRA_USER: ${{ secrets.JIRA_CLOUD_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_CLOUD_TOKEN }}
        run: |
          make DP1.tex openMilestones.tex
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make install_deps RTN-085.pdf'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf RTN-085.pdf --lsstdoc RTN-085.tex --ltd-product rtn-085
